<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>d17b451e-f7fd-4471-9d27-0089efc15600</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="4.0.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SetlistToPlaylist.Backend.Modules.Spotify.Abstractions\SetlistToPlaylist.Backend.Modules.Spotify.Abstractions.csproj" />
  </ItemGroup>

</Project>
