<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>0aec5b10-9fcf-4e2c-8319-431291cf758b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="4.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SetlistToPlaylist.Backend.Modules.SetlistFm.Abstractions\SetlistToPlaylist.Backend.Modules.SetlistFm.Abstractions.csproj" />
  </ItemGroup>

</Project>
